# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: busybox:latest


build1:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN dev.hbbx.de:4300
    - docker build -t dev.hbbx.de:4300/ev-manager/ev-manager-vue:latest .
    - docker push dev.hbbx.de:4300/ev-manager/ev-manager-vue:latest
  tags:
  - builder1

deploy1:
  stage: deploy
  script:
    - curl https://web3.hbbx.de/deployment/schoen/api.korbacher-energiezentrum.de/pITaR3m6FoWfE9VYeyw9QuaJfDwI9DmC
    - rm -r ./*
    - rm -r .e*
    - rm -r .g*
    - rm -r .d*
  tags:
    - builder1
